name: ETL-KafkaToClickhouse - Code verifying

on:
  push:
    branches:
      - master
    paths:
      - deploy/kafka_to_clickhouse/**
      - src/kafka_to_clickhouse/**
  pull_request:
    branches:
      - master
    paths:
      - deploy/kafka_to_clickhouse/**
      - src/kafka_to_clickhouse/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create directories
        run: |
          mkdir -p reports/kafka_to_clickhouse/styleguide/
          mkdir -p reports/kafka_to_clickhouse/mypy/

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install  wemake-python-styleguide flake8-html mypy lxml
        working-directory: deploy/kafka_to_clickhouse

      - name: Style checking
        run: |
          flake8 src/kafka_to_clickhouse --max-line-length 120 --exit-zero --format=html --htmldir=reports/kafka_to_clickhouse/styleguide/

      - name: Type checking
        run: |
          mypy --html-report reports/kafka_to_clickhouse/mypy/ src/kafka_to_clickhouse/* || true

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: code-verify-reports
          path: reports/

  notify:
    runs-on: ubuntu-latest
    if: cancelled() == false
    needs: build
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>${{ github.workflow }}</b>
            <b>Репозиторий:</b> <a href="https://github.com/${{github.repository}}">${{github.repository}}</a>
            <b>Статус:</b> ${{ needs.build.result }}
            <b>Детали:</b> <a href="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}">Просмотреть</a>
